ctest: add basic functional tests
vitalyvch/strace.ebpf pull request #2
Opened 2017-02-13 15:21 UTC by ldorau

2017-02-14 10:53 UTC, vitalyvch requested changes
Also please replace trace=kp-libc-all with trace=kp-kern-all

2017-02-14 10:53 UTC, vitalyvch commented on test/test_basic.c
> +	(void) fork();
You definitely should do here **syscall(SYS_fork)**

2017-02-14 11:39 UTC, ldorau commented
> Also please replace trace=kp-libc-all with trace=kp-kern-all
Why?

2017-02-14 12:11 UTC, ldorau commented
Fixed

2017-02-15 07:44 UTC, ldorau commented on test/test_basic.c
> +	(void) fork();
Done

2017-02-15 08:56 UTC, ldorau commented
Reopened in #3

2017-02-15 08:56 UTC, closed without merging